require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TripRequestsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TripRequest. As you add validations to TripRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TripRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all trip_requests as @trip_requests" do
      trip_request = TripRequest.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:trip_requests)).to eq([trip_request])
    end
  end

  describe "GET show" do
    it "assigns the requested trip_request as @trip_request" do
      trip_request = TripRequest.create! valid_attributes
      get :show, {:id => trip_request.to_param}, valid_session
      expect(assigns(:trip_request)).to eq(trip_request)
    end
  end

  describe "GET new" do
    it "assigns a new trip_request as @trip_request" do
      get :new, {}, valid_session
      expect(assigns(:trip_request)).to be_a_new(TripRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested trip_request as @trip_request" do
      trip_request = TripRequest.create! valid_attributes
      get :edit, {:id => trip_request.to_param}, valid_session
      expect(assigns(:trip_request)).to eq(trip_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TripRequest" do
        expect {
          post :create, {:trip_request => valid_attributes}, valid_session
        }.to change(TripRequest, :count).by(1)
      end

      it "assigns a newly created trip_request as @trip_request" do
        post :create, {:trip_request => valid_attributes}, valid_session
        expect(assigns(:trip_request)).to be_a(TripRequest)
        expect(assigns(:trip_request)).to be_persisted
      end

      it "redirects to the created trip_request" do
        post :create, {:trip_request => valid_attributes}, valid_session
        expect(response).to redirect_to(TripRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trip_request as @trip_request" do
        post :create, {:trip_request => invalid_attributes}, valid_session
        expect(assigns(:trip_request)).to be_a_new(TripRequest)
      end

      it "re-renders the 'new' template" do
        post :create, {:trip_request => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested trip_request" do
        trip_request = TripRequest.create! valid_attributes
        put :update, {:id => trip_request.to_param, :trip_request => new_attributes}, valid_session
        trip_request.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested trip_request as @trip_request" do
        trip_request = TripRequest.create! valid_attributes
        put :update, {:id => trip_request.to_param, :trip_request => valid_attributes}, valid_session
        expect(assigns(:trip_request)).to eq(trip_request)
      end

      it "redirects to the trip_request" do
        trip_request = TripRequest.create! valid_attributes
        put :update, {:id => trip_request.to_param, :trip_request => valid_attributes}, valid_session
        expect(response).to redirect_to(trip_request)
      end
    end

    describe "with invalid params" do
      it "assigns the trip_request as @trip_request" do
        trip_request = TripRequest.create! valid_attributes
        put :update, {:id => trip_request.to_param, :trip_request => invalid_attributes}, valid_session
        expect(assigns(:trip_request)).to eq(trip_request)
      end

      it "re-renders the 'edit' template" do
        trip_request = TripRequest.create! valid_attributes
        put :update, {:id => trip_request.to_param, :trip_request => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trip_request" do
      trip_request = TripRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => trip_request.to_param}, valid_session
      }.to change(TripRequest, :count).by(-1)
    end

    it "redirects to the trip_requests list" do
      trip_request = TripRequest.create! valid_attributes
      delete :destroy, {:id => trip_request.to_param}, valid_session
      expect(response).to redirect_to(trip_requests_url)
    end
  end

end
